"""empty message

Revision ID: 2737849cc090
Revises: 45c6d29ad41c
Create Date: 2020-05-16 13:06:00.208828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2737849cc090'
down_revision = '45c6d29ad41c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'course_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('course_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
