"""empty message

Revision ID: 511f037b3963
Revises: 547948f92b7c
Create Date: 2020-05-16 13:12:35.295356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511f037b3963'
down_revision = '547948f92b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'question')
    # ### end Alembic commands ###
