"""empty message

Revision ID: 547948f92b7c
Revises: 2737849cc090
Create Date: 2020-05-16 13:08:34.110837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547948f92b7c'
down_revision = '2737849cc090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('answered', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.drop_table('questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('question_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answered', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='questions_student_id_fkey'),
    sa.PrimaryKeyConstraint('question_id', name='questions_pkey')
    )
    op.drop_table('question')
    # ### end Alembic commands ###
