"""empty message

Revision ID: 7f4215a7d25c
Revises: 934f81221cba
Create Date: 2020-05-17 14:22:53.229602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4215a7d25c'
down_revision = '934f81221cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('extracted_tags', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'extracted_tags')
    # ### end Alembic commands ###
