"""empty message

Revision ID: 934f81221cba
Revises: 511f037b3963
Create Date: 2020-05-17 10:19:15.893330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934f81221cba'
down_revision = '511f037b3963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'created_date')
    # ### end Alembic commands ###
