"""empty message

Revision ID: c6f8921b26ce
Revises: 7be8c928a03e
Create Date: 2020-05-23 13:29:38.672915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f8921b26ce'
down_revision = '7be8c928a03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_module', 'admin_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('course_module', 'course_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('course_module', 'module_link',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('course_module', 'module_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_foreign_key(None, 'course_module', 'course', ['course_id'], ['course_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_module', type_='foreignkey')
    op.alter_column('course_module', 'module_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('course_module', 'module_link',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('course_module', 'course_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('course_module', 'admin_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
