"""empty message

Revision ID: ec6325968919
Revises: 7f4215a7d25c
Create Date: 2020-05-17 21:16:28.158024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec6325968919'
down_revision = '7f4215a7d25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('course_module', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('course_module', sa.Column('excluded_tags', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True))
    op.add_column('course_module', sa.Column('generated_tags', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True))
    op.add_column('student', sa.Column('created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'created_time')
    op.drop_column('course_module', 'generated_tags')
    op.drop_column('course_module', 'excluded_tags')
    op.drop_column('course_module', 'created_time')
    op.drop_column('course', 'created_time')
    # ### end Alembic commands ###
